# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Nombre')),
                ('motor', models.CharField(max_length=256, verbose_name='Motor')),
                ('cylinder', models.CharField(max_length=266, verbose_name='Cilindraje')),
                ('photo', models.ImageField(default='media/None/no-img.png', upload_to='media/')),
            ],
            options={
                'default_permissions': (),
                'verbose_name': 'Moto',
                'verbose_name_plural': 'Motos',
                'permissions': (('ver_moto', 'Puede ver las Motos'), ('editar_moto', 'Puede editar las motos'), ('borrar_moto', 'Puede borrar las motos')),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripci\xf3n')),
            ],
            options={
                'default_permissions': (),
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'permissions': (('ver_categorias', 'Puede ver las categorias'), ('editar_categorias', 'Puede editar las categorias'), ('borrar_categorias', 'Puede borrar las categorias')),
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo')),
                ('subjet', models.TextField(verbose_name='Asunto')),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Bike')),
            ],
            options={
                'default_permissions': (),
                'verbose_name': 'contacto',
                'verbose_name_plural': 'contactanos',
                'permissions': (('ver_contacto', 'Puede ver los contactos'), ('editar_moto', 'Puede editar los contactos'), ('borrar_moto', 'Puede borrar los contactos')),
            },
        ),
        migrations.AddField(
            model_name='bike',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Category'),
        ),
    ]
