# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='description',
            field=models.TextField(default='', verbose_name='Descripci\xf3n'),
            preserve_default=False,
        ),
    ]
