# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_bike_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Category', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='photo',
            field=models.ImageField(default='media/None/no-img.png', upload_to='media/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='bike',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Bike', verbose_name='Moto'),
        ),
    ]
