# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20170917_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='photo',
            field=models.ImageField(default='media/None/no-img.png', upload_to='media/motos/', verbose_name='Foto'),
        ),
    ]
