# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20170917_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='celphone',
            field=models.CharField(default='', max_length=256, verbose_name='Celular'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bike',
            name='photo',
            field=models.ImageField(default='None/no-img.png', upload_to='motos/', verbose_name='Foto'),
        ),
    ]
